services:
  - type: web
    name: weddingapp
    runtime: docker
    repo: https://github.com/BunyaminAslan/WeddingApp
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      - key: CLOUDINARY_CLOUDNAME
        value: your_cloud_name
      - key: CLOUDINARY_APIKEY
        value: your_api_key
      - key: CLOUDINARY_APISECRET
        value: your_api_secret
      - key: DB_CONNECTION_STRING
        value: your_connection_string
