services:
  - type: web
    name: weddingapp
    runtime: docker
    repo: https://github.com/BunyaminAslan/WeddingApp
    plan: free
    region: frankfurt
    dockerfilePath: dockerfile
    envVars:
      - key: CLOUDINARY_CLOUDNAME
        value: dmwlmdigc
      - key: CLOUDINARY_APIKEY
        value: 659553876844838
      - key: CLOUDINARY_APISECRET
        value: nvk-_C8ui0ohvLuaxo3bkW2FGYU
      - key: DB_CONNECTION_STRING
        value: User Id=postgres.ngfgtlfzrajjwrffhnlp;Password=f-9dmhyBK*;Server=aws-0-eu-north-1.pooler.supabase.com;Port=5432;Database=postgres